### ISSUE TITLE
how do add url camera?what do you mean url?

### ISSUE THREAD

**Issue by 8thstar** [nathan242/ipcam-cctv#3]
pleas one sample url

**Comment by 8thstar** [comment]
pleas help mr

**Comment by 8thstar** [comment]
i am problem to run your project
pleas help me to run in web server and add camera

**Comment by nathan242** [comment]
The URL is the path after the protocol. Most IP cameras use RTSP so you would need to set this to the RTSP URL for your device (e.g. /media/video1). You will need to get this from your device's documentation.
